print("User")
print(" ↓")
print("Application")
print(" ↓")
print("Logical File System")
print(" ↓")
print("File Organization Module")
print(" ↓")
print("Basic File System")
print(" ↓")
print("I/O Control")
print(" ↓")
print("Disk")